FROM ubuntu:focal as base
ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED 1
RUN apt-get update --fix-missing
RUN apt-get install -y python3 python3-pip
RUN pip3 install pipenv --upgrade


# UNIT TESTS
FROM base
WORKDIR /tests
COPY . /tests/
WORKDIR /tests/src/client
RUN pipenv install
RUN pipenv run python3 -m unittest discover tests


FROM base
WORKDIR /app
COPY src/client/main.py src/client/Pipfile src/client/Pipfile.lock /app/
RUN pipenv install
RUN pipenv check
ENTRYPOINT pipenv run python3 main.py