FROM ubuntu:focal as base
ENV LANG C.UTF-8
ENV PYTHONUNBUFFERED 1
RUN apt-get update --fix-missing
RUN apt-get install -y python3 python3-pip
RUN pip3 install pipenv --upgrade
WORKDIR /app
COPY src/server/main.py src/server/Pipfile src/server/Pipfile.lock /app/

# BANDIT & SECURITY CHECKS
FROM base
RUN pipenv install --dev
RUN pipenv check
RUN pipenv run bandit main.py

FROM base
RUN pipenv install
RUN pipenv check
ENTRYPOINT pipenv run python3 main.py